### ISSUE TITLE
HW5

### ISSUE THREAD

**Issue by cschaffner** [BasicProbability/BasicProbability.github.io#24]
In I.1 the function f(x)=2 is constant??

**Comment by cschaffner** [comment]
I.4. they have not formally heard what the "normal distribution" is and maybe not even that it exists...

**Comment by cschaffner** [comment]
II.1. shouldn't it always be week, you start off saying beers/day is 50 ?

In general, "10 number of beers sold" sounds to me like they are selling "10 different brands of beer" and not "10 bottles of (the same) beer". I've rephrased it slightly, but maybe more adjustments need to be done.

**Comment by brochhagen** [comment]
l.1: Yes, this was intended as a simple exercise on limits. 
l.4. Good point. In principle this is not relevant to solve the exercise, but it may be confusing. 
li.1. Typo, yes: day OR week everywhere (day seems more realistic). I'll also rephrase it. Thanks!

**Comment by cschaffner** [comment]
II.3. is tricky because one needs Lagrange multipliers to incorporate the constraint that the \theta_i sum to 1

**Comment by cschaffner** [comment]
but I don't see why II.4 has an exclamation mark, isn't it almost the same differentiation exercise as in the script? (as long as \alpha and \beta are considered constants that do not need to be optimized over)

**Comment by cschaffner** [comment]
II.2. is really easy, maybe ask to show that
$P( |X-\mu | < k \sqrt{\sigma^2} ) > (k^2 -1)/k^2$ instead?

**Comment by philschulz** [comment]
About II.4: yes the calculus behind MAP is the same as the calculus in the script. However, in the script we explicitly say that we are not going to do MAP because it involves continuous distributions over parameter (in this case the Beta distribution). This exercise asks them to do something that was left out of the script. So the exclamation mark is there for psychological rather than mathematical hardness. Also, if they are not familiar with differentiation and are just trying to emulate what is in the script, it may indeed be kinda hard. However, feel free to take away the exclamation mark if you feel like it is superfluous.
